version: '3.9'
services:
  service1:
    image: sample-express-app
    build: .
    expose:
      - "8001"
    networks:
      - backend
    ports:
      - "8001:8001"

  service2:
    image: sample-express-app
    networks:
      - backend
    ports:
      - "8004:8004"
    expose:
      - "8004"
    command: sh

networks:
  backend:
    driver: bridge